name: Test ASDF DVC
on:   
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "dvc --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADSF_DVC_DEBUG: "true"
